- name: Creating a database server
  Host: mysql
  become: yes

  tasks: 
  - name: Install Mysql
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: Enable and start Mysql
    ansible.builtin.service:
     name: mysql
     enabled: yes
     state: started


